### ISSUE TITLE
DriverBuddy entry does not shown in plugins menu

### ISSUE THREAD

**Issue by prksastry** [VoidSec/DriverBuddyReloaded#12]
I use IDA Pro 7.6 and Python 3.10, after copying the folder and py script, it should be appeared in Edit->Plugins, but I cannot see the plugin listed?, exact for which IDA and Python versions, will this work?

**Comment by VoidSec** [comment]
@prksastry Hi, DriverBuddyReloaded has been tested on IDA 7.6.210427 and python 3.9.6.
Did you copy both the ` DriverBuddyReloaded` folder and the `DriverBuddyReloaded.py` file into the IDA plugins folder?
Does IDA output window print out any error message?
Try to run the `idapyswitch ` binary (**from admin command prompt**) and let me know if it solve the issue.

**Comment by VoidSec** [comment]
Closing the issue as I'm not hearing back from you. In case, just re-open it.
