### ISSUE TITLE
Python Version Compatibility for IDA Plugin

### ISSUE THREAD

**Issue by ocher18** [VoidSec/DriverBuddyReloaded#33]
I've been attempting to integrate the "Driver Buddy Reloaded" plugin into IDA Pro 7.5, following the installation instructions meticulously including " Python v. 3.x, run the idapyswitch.exe binary (located in IDA's folder) from an admin command prompt " . However, despite adding the plugin files to the correct directory and ensuring Python is correctly configured and added to my system's PATH, I'm encountering issues with the plugin not appearing in IDA Pro 7.5.

Could you please confirm the specific Python version compatibility required for the plugin to function correctly with IDA Pro 7.5?

Thank you for your assistance. I look forward to your response.

Best regards,

**Comment by VoidSec** [comment]
Hi, in which folder are you placing the script? What error message, if any, form the IDA console?
